### ISSUE TITLE
Block Users and don't show user if they can't send email to that person. 

### ISSUE THREAD

**Issue by jeremiahtenbrink** [humhub/humhub-modules-mail#116] opened 2017-02-02 02:14 UTC
It would be nice to have the ability to block users from contacting you if they are harassing you. I guess this could be done in the friendship module as well and then just not allow them to see your profile anymore if you block them. 

However with that being said. I would like to see a configuration page where the admin can set the default message settings for new users. I would also like to see the drop down box in new mail not show people if they can't be messaged. Like if they aren't accepting messages from anyone other than friends, and I'm not a friend with them, why does it still show their name on the drop down. Or at least there should be something that says they aren't accepting messages from individuals not their friend. 

![capture](https://cloud.githubusercontent.com/assets/17443353/22534570/2e0eff86-e8b2-11e6-9fa9-6990ad7e19c1.JPG)

**Comment by buddh4** [comment] 2017-02-07 12:21
This is a known issue and will be implemented soon, in v1.2 there will be an additional tooltip which informs you why this user is disabled. In my opinion this is more obvious than removing the user from the result.

**Comment by buddh4** [comment] 2017-02-07 12:22
also duplicate of https://github.com/humhub/humhub-modules-mail/issues/110

**Closed by buddh4** 2017-02-07 12:22 UTC
