### ISSUE TITLE
Delay on send message

### ISSUE THREAD

**Issue by allocenx** [humhub/humhub-modules-mail#60] opened 2015-10-28 15:11 UTC
As title says, when i click on send button there is a short delay but noticeable and than redirects to the mail page, why it does that? Its a bug does not it?

**Comment by feldrim** [comment] 2015-12-06 17:56
It could be done without reloading page I guess. Maybe some ajax stuff could do that. At least it would look cool while waiting on that delay period.

**Comment by buddh4** [comment] 2018-11-15 15:40
Duplicate of https://github.com/humhub/humhub-modules-mail/issues/16

**Closed by buddh4** 2018-11-15 15:40 UTC
Labels: enhancement
